# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'templates\base_wind.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont


class BaseWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 550)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_btn.setObjectName("start_btn")
        self.verticalLayout_2.addWidget(self.start_btn)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout.addWidget(self.comboBox_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.horizontalLayout_6.addWidget(self.comboBox_3)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser.setFont(QFont('Arial', 12))
        self.verticalLayout_2.addWidget(self.textBrowser)
        self.graph_btn = QtWidgets.QPushButton(self.centralwidget)
        self.graph_btn.setObjectName("graph_btn")
        self.verticalLayout_2.addWidget(self.graph_btn)
        self.export_btn = QtWidgets.QPushButton(self.centralwidget)
        self.export_btn.setObjectName("export_btn")
        self.verticalLayout_2.addWidget(self.export_btn)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Запустить"))
        self.export_btn.setText(_translate("MainWindow", "Экспортировать файл"))
        self.start_btn.setText(_translate("MainWindow", "Подключиться к БД"))
        self.graph_btn.setText(_translate("MainWindow", "Показать график"))
        self.pushButton.setFont(QFont('Arial', 13))
        self.export_btn.setFont(QFont('Arial', 13))
        self.start_btn.setFont(QFont('Arial', 13))
        self.graph_btn.setFont(QFont('Arial', 13))
        self.comboBox.setFont(QFont('Arial', 13))
        self.comboBox_2.setFont(QFont('Arial', 13))
        self.comboBox_3.setFont(QFont('Arial', 13))
        self.export_btn.setEnabled(False)